/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2020-06-11 05:51:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1591772721928L));
    _jspx_dependants.put("jar:file:/C:/Users/rudtj/Desktop/EEE_UK/workspace/Cloude_Templer/web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("   \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/css/Style-signUp.css\">\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("<script src=\"../js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#idCheck {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#idCheck:hover {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#idCheck, #goMain, #joinBtn {\r\n");
      out.write("\tbackground: #d3d3d3;\r\n");
      out.write("\tcolor: gray;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\twidth: 80px;\r\n");
      out.write("\theight: 25px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#idCheck:hover, #joinBtn:hover, #goMain:hover {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#joinBtn {\r\n");
      out.write("\tbackground: yellowgreen;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#joinBtn, #goMain {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/menubar.jsp", out, false);
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t\t<form id=\"joinForm\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/insert.me\"\r\n");
      out.write("\t\t\tmethod=\"post\" onsubmit=\"return insertMember()\">\r\n");
      out.write("\t\t\t<!--section1-->\r\n");
      out.write("\t\t\t<div class=\"section1\" style=\"padding-bottom: 90px;\">\r\n");
      out.write("\t\t\t\t<h1 style=\"color: black;\">JOIN</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<hr style=\"border: 1px soild black;\">\r\n");
      out.write("\t\t\t\t<span>회원 가입<a style=\"color: red; font-size: 15px;\">*</a></span>\r\n");
      out.write("\t\t\t\t<hr style=\"border: 1px soild black;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"artregi-infobox\">\r\n");
      out.write("\t\t\t\t\t<div class=\"info-box1\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"labelfirst\" id=\"name\">이름<a\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"color: red; font-size: 15px;\">*</a></label><input\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"nomal-text\" type=\"text\" id=\"userName\" name=\"userName\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"NAME\" required>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"info-box2\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"labelfirst\">아이디<a style=\"color: red; font-size: 15px;\">*</a></label>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"nomal-text\" type=\"text\" id=\"userId\" name=\"userId\" required>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"idresult\" style=\"font-size: 13px; float: right;\">영어,숫자\r\n");
      out.write("\t\t\t\t\t\t상관없이 4글자이상 입력하세요.</div>\r\n");
      out.write("\t\t\t\t\t<br> <br>\r\n");
      out.write("\t\t\t\t\t<div id=\"idCheck\" style=\"float: right; width: 100px; height: 20px; background-color: gray; text-align: center; color: white;\">중복확인</div>\r\n");
      out.write("\t\t\t\t\t<br> <br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"info-box3\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"labelfirst\">비밀번호<a\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"color: red; font-size: 15px;\">*</a></label> <input\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"nomal-text\" type=\"password\" id=\"userPwd\" name=\"userPwd\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"PASSWORD\" required>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"pwdresult\" style=\"font-size: 13px; float: right;\">영어,숫자\r\n");
      out.write("\t\t\t\t\t\t포함해서 6글자 이상 입력하세요.</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"info-box4\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"labelfirst\">비밀번호 확인<a\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"color: red; font-size: 15px;\">*</a></label> <input\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"nomal-text\" type=\"password\" id=\"userPwd2\" name=\"userPwd2\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"confirm password\" required>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"pwdcheck\" style=\"font-size: 13px; float: right;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<br> <br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"info-box5\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"labelfirst\">닉네임</label><input class=\"nomal-text\"\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\" id=\"nickName\" name=\"nickName\" placeholder=\"NICKNAME\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"info-box6\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"labelfirst\">휴대폰 번호</label>\r\n");
      out.write("\t\t\t\t\t\t&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"tel\" id=\"phone\" name=\"phone\" maxlength=\"11\"\r\n");
      out.write("\t\t\t\t\t\t\tautocomplete=\"off\" placeholder=\"(-)없이 휴대폰 번호 기재\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"height: 25px; width: 280px; float: right;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"info-box7\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"labelfirst\">주소<a\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"color: red; font-size: 15px;\">*</a></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"float:right;\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"sample6_postcode\" name=\"sample6_postcode\"  placeholder=\"우편번호\" style=\"width:188px;height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" onclick=\"sample6_execDaumPostcode()\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"우편번호 찾기\" style=\"height:30px;\"><br> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"sample6_address\"  name=\"sample6_address\"  placeholder=\"주소\" style=\"width:188px;height:30px;\"><br> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"text\" id=\"sample6_detailAddress\" name=\"sample6_detailAddress\" placeholder=\"상세주소\" style=\"width:188px;height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"sample6_extraAddress\" name=\"sample6_extraAddress\" placeholder=\"참고항목\" style=\"width:85px;height:30px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("<br><br><br><br>\r\n");
      out.write("\t\t\t\t\t<div class=\"info-box7\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"labelfirst\">이메일<a\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"color: red; font-size: 15px;\">*</a></label><input\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"nomal-text\" type=\"email\" id=\"email\" name=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"@ 포함한 이메일 기재\" required>\r\n");
      out.write("\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- infobox 끝 -->\r\n");
      out.write("\t\t\t\t<br> <br>\r\n");
      out.write("\t\t\t\t<div class=\"submit-box\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t<div id=\"goMain\" onclick=\"goMain();\">메인으로</div>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"가입하기\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 280px; height: 30px; color: white; background: #cc0000\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"checkId()\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"checkTest\" value=\"0\">\r\n");
      out.write("\t\t\t\t<!-- submit-box 끝 -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- section 끝-->\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- container 끝-->\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\tfunction goMain(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertMember(){\r\n");
      out.write("\t\t      //아이디 중복 확인\r\n");
      out.write("\t\t       if($(\"#checkTest\").val() != \"0\"){\r\n");
      out.write("\t\t         return true;\r\n");
      out.write("\t\t      }else{\r\n");
      out.write("\t\t         alert(\"중복확인 버튼을 체크해 주세요\");\r\n");
      out.write("\t\t         return false;\r\n");
      out.write("\t\t      }\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\r\n");
      out.write("\t   $(function(){\r\n");
      out.write("\t          $(\"#userId\").change(function(){\r\n");
      out.write("\t             $(\"#checkTest\").val(0);\r\n");
      out.write("\t             $(\"#idCheck\").css(\"background-color\",\"gray\");\r\n");
      out.write("\t          });\r\n");
      out.write("\t     \r\n");
      out.write("\t          $(\"#idCheck\").click(function(){\r\n");
      out.write("\t             $(\"#checkTest\").val(1);\r\n");
      out.write("\t             var userId = $(\"#userId\").val();\r\n");
      out.write("\t              alert(userId);\r\n");
      out.write("\t             if(!userId || userId.length < 4){\r\n");
      out.write("\t                alert(\"아이디는 최소 4자리 이상이어야합니다.\");\r\n");
      out.write("\t                userId.focus();\r\n");
      out.write("\t             }else{\r\n");
      out.write("\t                $.ajax({\r\n");
      out.write("\t                   url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/idCheck.me\",\r\n");
      out.write("\t                  type : \"post\",\r\n");
      out.write("\t                  data : {userId:userId},\r\n");
      out.write("\t                  success : function(data) {\r\n");
      out.write("\t                \t  if (data == 'fail') {\r\n");
      out.write("\t\t                        alert(\"아이디가 중복 됩니다.\");\r\n");
      out.write("\t\t                        userId.focus();\r\n");
      out.write("\t\t                     } else {\r\n");
      out.write("\t\t                        alert(\"아이디가 사용가능합니다.\");\r\n");
      out.write("\t\t                        idCheck = 1;\r\n");
      out.write("\t\t                        $(\"#idCheck\").css(\"background-color\",\"red\");   //색을 빨간색으로 바꿔줌\r\n");
      out.write("\t\t                     }\r\n");
      out.write("\t\t                    \r\n");
      out.write("\t                  },\r\n");
      out.write("\t                  error : function(data) {\r\n");
      out.write("\t                     console.log(\"서버 통신 안됨\");\r\n");
      out.write("\t                  }\r\n");
      out.write("\r\n");
      out.write("\t               })\r\n");
      out.write("\t            }\r\n");
      out.write("\t         })\r\n");
      out.write("\r\n");
      out.write("\t      });// ajax 중복\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
